### ISSUE TITLE
publish to docker hub for easy reuse

### ISSUE THREAD

**Issue by ssbarnea** [wandhydrant/folding-at-home-docker-gpu#1]
Please publish it to hub.docker.com so we can easily reuse it.

**Comment by wandhydrant** [comment]
Hello, happy that this Dockerfile is useful!

Sorry, I'm generally not confortable with redistributing binaries that I have not written myself. In the case of Folding@home it might even be forbidden - they want to be the only ones distributing binaries.

> Re-distributing the FAH files or packaging the FAH files inside another software package in a attempt to install FAH with or without the user’s consent is a violation of the EULA. 

https://foldingathome.org/support/faq/rules-policies/

Is it not feasible for you to run the "docker build" line yourself?

**Comment by ssbarnea** [comment]
I am already using another container which had no problem with that.  I doubt they will chaise anyone about doing a container for them, unless someone would really do some nasty things.

I prefer to just pull a container instead of building it, mainly due to speed but also because I start it on various hosts remotely.

**Comment by wandhydrant** [comment]
Sorry, regardless of what other containers do, I won't do something I don't have the rights for and which is expressly forbidden in their FAQ. This is not open-source software that one is free to redistribute.
